import CapsuleCatalog
import Foundation

// Internal conversions between the Swift-native catalog model types and the
// raw UniFFI record types. Kept in one place, all `internal`: the FFI record
// types never appear in this module's public API — only these conversions and
// `CapsuleCatalog` itself touch them.

// MARK: - CatalogAsset ⇄ AssetRecord

extension CatalogAsset {
    init(_ record: AssetRecord) {
        self.init(
            id: record.uuid,
            assetType: record.assetType,
            captureTimestamp: record.captureTimestamp,
            importTimestamp: record.importTimestamp,
            hashSHA256: record.hashSha256,
            captureUTC: record.captureUtc,
            captureTimezoneSource: record.captureTzSource,
            width: record.width,
            height: record.height,
            durationMillis: record.durationMs,
            stackID: record.stackId,
            isStackHidden: record.isStackHidden,
            chromahash: record.chromahash,
            dominantColor: record.dominantColor,
            albumID: record.albumId,
            rating: record.rating,
            isDeleted: record.isDeleted,
            deletedAt: record.deletedAt,
            isHidden: record.isHidden
        )
    }

    var ffiRecord: AssetRecord {
        AssetRecord(
            uuid: id,
            assetType: assetType,
            captureTimestamp: captureTimestamp,
            captureUtc: captureUTC,
            captureTzSource: captureTimezoneSource,
            importTimestamp: importTimestamp,
            hashSha256: hashSHA256,
            width: width,
            height: height,
            durationMs: durationMillis,
            stackId: stackID,
            isStackHidden: isStackHidden,
            chromahash: chromahash,
            dominantColor: dominantColor,
            albumId: albumID,
            rating: rating,
            isDeleted: isDeleted,
            deletedAt: deletedAt,
            isHidden: isHidden
        )
    }
}

// MARK: - CatalogAlbum ⇄ AlbumRecord

extension CatalogAlbum {
    init(_ record: AlbumRecord) {
        self.init(
            id: record.id,
            name: record.name,
            createdAt: record.createdAt,
            modifiedAt: record.modifiedAt,
            coverAssetID: record.coverAssetId
        )
    }

    var ffiRecord: AlbumRecord {
        AlbumRecord(
            id: id,
            name: name,
            createdAt: createdAt,
            modifiedAt: modifiedAt,
            coverAssetId: coverAssetID
        )
    }
}

// MARK: - CatalogStack ⇄ AssetStackRecord

extension CatalogStack {
    init(_ record: AssetStackRecord) {
        self.init(
            id: record.id,
            stackType: record.stackType,
            primaryAssetID: record.primaryAssetId,
            coverAssetID: record.coverAssetId,
            isCollapsed: record.isCollapsed,
            isAutoGenerated: record.isAutoGenerated,
            createdAt: record.createdAt,
            modifiedAt: record.modifiedAt
        )
    }

    var ffiRecord: AssetStackRecord {
        AssetStackRecord(
            id: id,
            stackType: stackType,
            primaryAssetId: primaryAssetID,
            coverAssetId: coverAssetID,
            isCollapsed: isCollapsed,
            isAutoGenerated: isAutoGenerated,
            createdAt: createdAt,
            modifiedAt: modifiedAt
        )
    }
}

// MARK: - CatalogStackMember ⇄ StackMemberRecord

extension CatalogStackMember {
    init(_ record: StackMemberRecord) {
        self.init(
            id: record.id,
            stackID: record.stackId,
            assetID: record.assetId,
            sequenceOrder: record.sequenceOrder,
            memberRole: record.memberRole,
            createdAt: record.createdAt
        )
    }

    var ffiRecord: StackMemberRecord {
        StackMemberRecord(
            id: id,
            stackId: stackID,
            assetId: assetID,
            sequenceOrder: sequenceOrder,
            memberRole: memberRole,
            createdAt: createdAt
        )
    }
}
