import Foundation

// Internal conversions between the Swift-native catalog model types and the
// raw UniFFI record types. Kept in one place, all `internal`: the FFI record
// types never appear in this module's public API — only these conversions and
// `CapsuleCatalog` itself touch them.

// MARK: - CatalogAsset ⇄ AssetRecord

extension CatalogAsset {
    init(_ record: AssetRecord) {
        self.init(
            id: record.uuid,
            assetType: record.assetType,
            captureTimestamp: record.captureTimestamp,
            importTimestamp: record.importTimestamp,
            hashSHA256: record.hashSha256,
            captureUTC: record.captureUtc,
            captureTimezoneSource: record.captureTzSource,
            width: record.width,
            height: record.height,
            durationMillis: record.durationMs,
            stackID: record.stackId,
            isStackHidden: record.isStackHidden,
            chromahash: record.chromahash,
            dominantColor: record.dominantColor,
            albumID: record.albumId,
            rating: record.rating,
            isDeleted: record.isDeleted,
            deletedAt: record.deletedAt
        )
    }

    var ffiRecord: AssetRecord {
        AssetRecord(
            uuid: id,
            assetType: assetType,
            captureTimestamp: captureTimestamp,
            captureUtc: captureUTC,
            captureTzSource: captureTimezoneSource,
            importTimestamp: importTimestamp,
            hashSha256: hashSHA256,
            width: width,
            height: height,
            durationMs: durationMillis,
            stackId: stackID,
            isStackHidden: isStackHidden,
            chromahash: chromahash,
            dominantColor: dominantColor,
            albumId: albumID,
            rating: rating,
            isDeleted: isDeleted,
            deletedAt: deletedAt
        )
    }
}

// MARK: - CatalogAlbum ⇄ AlbumRecord

extension CatalogAlbum {
    init(_ record: AlbumRecord) {
        self.init(
            id: record.id,
            name: record.name,
            createdAt: record.createdAt,
            modifiedAt: record.modifiedAt,
            coverAssetID: record.coverAssetId
        )
    }

    var ffiRecord: AlbumRecord {
        AlbumRecord(
            id: id,
            name: name,
            createdAt: createdAt,
            modifiedAt: modifiedAt,
            coverAssetId: coverAssetID
        )
    }
}

// MARK: - CatalogStack ⇄ AssetStackRecord

extension CatalogStack {
    init(_ record: AssetStackRecord) {
        self.init(
            id: record.id,
            stackType: record.stackType,
            primaryAssetID: record.primaryAssetId,
            coverAssetID: record.coverAssetId,
            isCollapsed: record.isCollapsed,
            isAutoGenerated: record.isAutoGenerated,
            createdAt: record.createdAt,
            modifiedAt: record.modifiedAt
        )
    }

    var ffiRecord: AssetStackRecord {
        AssetStackRecord(
            id: id,
            stackType: stackType,
            primaryAssetId: primaryAssetID,
            coverAssetId: coverAssetID,
            isCollapsed: isCollapsed,
            isAutoGenerated: isAutoGenerated,
            createdAt: createdAt,
            modifiedAt: modifiedAt
        )
    }
}

// MARK: - CatalogStackMember ⇄ StackMemberRecord

extension CatalogStackMember {
    init(_ record: StackMemberRecord) {
        self.init(
            id: record.id,
            stackID: record.stackId,
            assetID: record.assetId,
            sequenceOrder: record.sequenceOrder,
            memberRole: record.memberRole,
            createdAt: record.createdAt
        )
    }

    var ffiRecord: StackMemberRecord {
        StackMemberRecord(
            id: id,
            stackId: stackID,
            assetId: assetID,
            sequenceOrder: sequenceOrder,
            memberRole: memberRole,
            createdAt: createdAt
        )
    }
}

// MARK: - CatalogStackHint ⇄ StackHintRecord

extension CatalogStackHint {
    init(_ record: StackHintRecord) {
        self.init(
            detectionKey: record.detectionKey,
            detectionMethod: record.detectionMethod,
            memberRole: record.memberRole,
            stackType: record.stackType
        )
    }

    var ffiRecord: StackHintRecord {
        StackHintRecord(
            detectionKey: detectionKey,
            detectionMethod: detectionMethod,
            memberRole: memberRole,
            stackType: stackType
        )
    }
}

// MARK: - CatalogSidecar ⇄ AssetSidecarRecord

extension CatalogSidecar {
    init(_ record: AssetSidecarRecord) {
        self.init(
            version: record.version,
            uuid: record.uuid,
            assetType: record.assetType,
            originalFilename: record.originalFilename,
            importTimestamp: record.importTimestamp,
            modifiedTimestamp: record.modifiedTimestamp,
            hashSHA256: record.hashSha256,
            fileSize: record.fileSize,
            isDeleted: record.isDeleted,
            rating: record.rating,
            tags: record.tags,
            importMode: record.importMode,
            importerVersion: record.importerVersion,
            rawshiftVersion: record.rawshiftVersion,
            captureTimestamp: record.captureTimestamp,
            captureUTC: record.captureUtc,
            captureTimezone: record.captureTz,
            captureTimezoneSource: record.captureTzSource,
            timezoneDatabaseVersion: record.tzDbVersion,
            width: record.width,
            height: record.height,
            durationMillis: record.durationMs,
            stackHint: record.stackHint.map(CatalogStackHint.init),
            albumID: record.albumId,
            deletedAt: record.deletedAt,
            cameraMake: record.cameraMake,
            cameraModel: record.cameraModel,
            gpsLatitude: record.gpsLat,
            gpsLongitude: record.gpsLon,
            unknownFieldsCBOR: record.unknownFieldsCbor
        )
    }

    var ffiRecord: AssetSidecarRecord {
        AssetSidecarRecord(
            version: version,
            uuid: uuid,
            assetType: assetType,
            originalFilename: originalFilename,
            importTimestamp: importTimestamp,
            modifiedTimestamp: modifiedTimestamp,
            hashSha256: hashSHA256,
            fileSize: fileSize,
            isDeleted: isDeleted,
            rating: rating,
            tags: tags,
            importMode: importMode,
            importerVersion: importerVersion,
            rawshiftVersion: rawshiftVersion,
            captureTimestamp: captureTimestamp,
            captureUtc: captureUTC,
            captureTz: captureTimezone,
            captureTzSource: captureTimezoneSource,
            tzDbVersion: timezoneDatabaseVersion,
            width: width,
            height: height,
            durationMs: durationMillis,
            stackHint: stackHint?.ffiRecord,
            albumId: albumID,
            deletedAt: deletedAt,
            cameraMake: cameraMake,
            cameraModel: cameraModel,
            gpsLat: gpsLatitude,
            gpsLon: gpsLongitude,
            unknownFieldsCbor: unknownFieldsCBOR
        )
    }
}
