/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as UOpaqueIdRouteImport } from './routes/u/$opaqueId'
import { Route as SOpaqueIdRouteImport } from './routes/s/$opaqueId'
import { Route as AlbumsIdRouteImport } from './routes/albums/$id'

const StorageLazyRouteImport = createFileRoute('/storage')()
const SharingLazyRouteImport = createFileRoute('/sharing')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const PhotosLazyRouteImport = createFileRoute('/photos')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ExploreLazyRouteImport = createFileRoute('/explore')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const SettingsSecurityLazyRouteImport = createFileRoute('/settings/security')()
const LibraryTrashLazyRouteImport = createFileRoute('/library/trash')()
const LibraryFavoritesLazyRouteImport = createFileRoute('/library/favorites')()
const LibraryArchiveLazyRouteImport = createFileRoute('/library/archive')()

const StorageLazyRoute = StorageLazyRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/storage.lazy').then((d) => d.Route))
const SharingLazyRoute = SharingLazyRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sharing.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const PhotosLazyRoute = PhotosLazyRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/photos.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ExploreLazyRoute = ExploreLazyRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/explore.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityLazyRoute = SettingsSecurityLazyRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/security.lazy').then((d) => d.Route),
)
const LibraryTrashLazyRoute = LibraryTrashLazyRouteImport.update({
  id: '/library/trash',
  path: '/library/trash',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/library/trash.lazy').then((d) => d.Route))
const LibraryFavoritesLazyRoute = LibraryFavoritesLazyRouteImport.update({
  id: '/library/favorites',
  path: '/library/favorites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/library/favorites.lazy').then((d) => d.Route),
)
const LibraryArchiveLazyRoute = LibraryArchiveLazyRouteImport.update({
  id: '/library/archive',
  path: '/library/archive',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/library/archive.lazy').then((d) => d.Route),
)
const UOpaqueIdRoute = UOpaqueIdRouteImport.update({
  id: '/u/$opaqueId',
  path: '/u/$opaqueId',
  getParentRoute: () => rootRouteImport,
} as any)
const SOpaqueIdRoute = SOpaqueIdRouteImport.update({
  id: '/s/$opaqueId',
  path: '/s/$opaqueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/explore': typeof ExploreLazyRoute
  '/login': typeof LoginLazyRoute
  '/photos': typeof PhotosLazyRoute
  '/settings': typeof SettingsLazyRouteWithChildren
  '/sharing': typeof SharingLazyRoute
  '/storage': typeof StorageLazyRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/s/$opaqueId': typeof SOpaqueIdRoute
  '/u/$opaqueId': typeof UOpaqueIdRoute
  '/library/archive': typeof LibraryArchiveLazyRoute
  '/library/favorites': typeof LibraryFavoritesLazyRoute
  '/library/trash': typeof LibraryTrashLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/albums/': typeof AlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/explore': typeof ExploreLazyRoute
  '/login': typeof LoginLazyRoute
  '/photos': typeof PhotosLazyRoute
  '/settings': typeof SettingsLazyRouteWithChildren
  '/sharing': typeof SharingLazyRoute
  '/storage': typeof StorageLazyRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/s/$opaqueId': typeof SOpaqueIdRoute
  '/u/$opaqueId': typeof UOpaqueIdRoute
  '/library/archive': typeof LibraryArchiveLazyRoute
  '/library/favorites': typeof LibraryFavoritesLazyRoute
  '/library/trash': typeof LibraryTrashLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/albums': typeof AlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/explore': typeof ExploreLazyRoute
  '/login': typeof LoginLazyRoute
  '/photos': typeof PhotosLazyRoute
  '/settings': typeof SettingsLazyRouteWithChildren
  '/sharing': typeof SharingLazyRoute
  '/storage': typeof StorageLazyRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/s/$opaqueId': typeof SOpaqueIdRoute
  '/u/$opaqueId': typeof UOpaqueIdRoute
  '/library/archive': typeof LibraryArchiveLazyRoute
  '/library/favorites': typeof LibraryFavoritesLazyRoute
  '/library/trash': typeof LibraryTrashLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/albums/': typeof AlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/photos'
    | '/settings'
    | '/sharing'
    | '/storage'
    | '/albums/$id'
    | '/s/$opaqueId'
    | '/u/$opaqueId'
    | '/library/archive'
    | '/library/favorites'
    | '/library/trash'
    | '/settings/security'
    | '/albums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/photos'
    | '/settings'
    | '/sharing'
    | '/storage'
    | '/albums/$id'
    | '/s/$opaqueId'
    | '/u/$opaqueId'
    | '/library/archive'
    | '/library/favorites'
    | '/library/trash'
    | '/settings/security'
    | '/albums'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/photos'
    | '/settings'
    | '/sharing'
    | '/storage'
    | '/albums/$id'
    | '/s/$opaqueId'
    | '/u/$opaqueId'
    | '/library/archive'
    | '/library/favorites'
    | '/library/trash'
    | '/settings/security'
    | '/albums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  ExploreLazyRoute: typeof ExploreLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PhotosLazyRoute: typeof PhotosLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRouteWithChildren
  SharingLazyRoute: typeof SharingLazyRoute
  StorageLazyRoute: typeof StorageLazyRoute
  AlbumsIdRoute: typeof AlbumsIdRoute
  SOpaqueIdRoute: typeof SOpaqueIdRoute
  UOpaqueIdRoute: typeof UOpaqueIdRoute
  LibraryArchiveLazyRoute: typeof LibraryArchiveLazyRoute
  LibraryFavoritesLazyRoute: typeof LibraryFavoritesLazyRoute
  LibraryTrashLazyRoute: typeof LibraryTrashLazyRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityLazyRouteImport
      parentRoute: typeof SettingsLazyRoute
    }
    '/library/trash': {
      id: '/library/trash'
      path: '/library/trash'
      fullPath: '/library/trash'
      preLoaderRoute: typeof LibraryTrashLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/favorites': {
      id: '/library/favorites'
      path: '/library/favorites'
      fullPath: '/library/favorites'
      preLoaderRoute: typeof LibraryFavoritesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/archive': {
      id: '/library/archive'
      path: '/library/archive'
      fullPath: '/library/archive'
      preLoaderRoute: typeof LibraryArchiveLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$opaqueId': {
      id: '/u/$opaqueId'
      path: '/u/$opaqueId'
      fullPath: '/u/$opaqueId'
      preLoaderRoute: typeof UOpaqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$opaqueId': {
      id: '/s/$opaqueId'
      path: '/s/$opaqueId'
      fullPath: '/s/$opaqueId'
      preLoaderRoute: typeof SOpaqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$id': {
      id: '/albums/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsLazyRouteChildren {
  SettingsSecurityLazyRoute: typeof SettingsSecurityLazyRoute
}

const SettingsLazyRouteChildren: SettingsLazyRouteChildren = {
  SettingsSecurityLazyRoute: SettingsSecurityLazyRoute,
}

const SettingsLazyRouteWithChildren = SettingsLazyRoute._addFileChildren(
  SettingsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  ExploreLazyRoute: ExploreLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PhotosLazyRoute: PhotosLazyRoute,
  SettingsLazyRoute: SettingsLazyRouteWithChildren,
  SharingLazyRoute: SharingLazyRoute,
  StorageLazyRoute: StorageLazyRoute,
  AlbumsIdRoute: AlbumsIdRoute,
  SOpaqueIdRoute: SOpaqueIdRoute,
  UOpaqueIdRoute: UOpaqueIdRoute,
  LibraryArchiveLazyRoute: LibraryArchiveLazyRoute,
  LibraryFavoritesLazyRoute: LibraryFavoritesLazyRoute,
  LibraryTrashLazyRoute: LibraryTrashLazyRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
