//! Capsule client SDK: the sanctioned network path for every Capsule client
//! (upload protocol, sync/download, auth flows).
//!
//! # REST client generation (spargen; slice `S-D8` in the repo-root `SLICES.md`)
//!
//! The typed REST client ([`rest`]) is generated from the server's **OpenAPI 3.1** schema by
//! `spargen`, our in-house generator, at build time (see `build.rs`). The previous progenitor
//! pipeline is gone deliberately: progenitor consumes OpenAPI 3.0 only, which forced a lossy
//! 3.1→3.0 schema down-conversion — a standing source of drift and failures. We do not
//! downgrade schemas. [`client::AuthenticatedClient`] wraps the generated `Client`, composing
//! it with [`auth`]'s session/token store so callers issue typed calls and never juggle raw
//! tokens. The hand-written upload/sync surfaces ([`upload`], [`sync`]) stay hand-written —
//! their protocols are too stateful for request/response codegen; the generated client covers
//! the plain request/response surfaces (auth, quota, storage-verify, receipts, devices, …).

pub mod albums;
pub mod auth;
pub mod client;
pub mod cohort;
pub mod fetch;
pub mod net;
pub mod peering;
pub mod push;
pub mod recovery;
pub mod staged;
pub mod sync;
pub mod upload;
pub mod verify;

/// An in-process mock HTTP server shared by the hand-written wire clients' tests.
#[cfg(test)]
mod testmock;

/// The typed REST client generated by `spargen` from the server's committed OpenAPI **3.1**
/// schema (`openapi.json`), emitted into `OUT_DIR` by `build.rs` and included verbatim here
/// (slice `S-D8`). One `async` method per operation, typed models, typed errors, and an
/// embedded freestanding `reqwest` runtime — `spargen` never enters the runtime dependency
/// tree. Do not edit: regenerate the schema with `mise run openapi`; the client re-generates
/// on every build. The ergonomic, session-composed entry point is
/// [`client::AuthenticatedClient`]; reach for [`rest::Client`] directly only for
/// unauthenticated calls.
pub mod rest {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        missing_docs,
        unreachable_pub,
        dead_code
    )]
    include!(concat!(env!("OUT_DIR"), "/rest_client.rs"));
}

/// uniffi surface over the SDK's user-flow primitives (login → upload → status →
/// sync) for Swift/Kotlin/Linux consumers (`ffi` feature, slice `S-D9`). A thin,
/// async-capable wrapper over [`auth`], [`upload`], and [`sync`]; tokens never
/// cross the boundary (the session-handle pattern). See [`ffi`].
#[cfg(feature = "ffi")]
pub mod ffi;

#[cfg(feature = "ffi")]
uniffi::setup_scaffolding!();

/// Generated gRPC client stubs for the key-free sync feed
/// (`capsule.sync.v1.SyncService`). The proto is single-sourced from the sync
/// server crate (slice `S-C2`) and compiled client-only by `build.rs`; the
/// ergonomic consumer over this stub lives in [`sync`].
pub mod proto {
    /// `capsule.sync.v1` — the key-free sync feed contract (slice `S-C2`).
    pub mod capsule {
        pub mod sync {
            pub mod v1 {
                #![allow(clippy::pedantic, unreachable_pub)]
                tonic::include_proto!("capsule.sync.v1");
            }
        }
    }
}

// `AuthenticatedClient` (revived over the generated `rest::Client`, composed with the S-D7
// session store) now lives in [`client`]; the parked comment block it replaced is gone.
