/**
 * The `/reference/` page table — the one place the reference section's shape is decided.
 *
 * `design/developer-docs.md` requires the `Reference` sidebar to be hand-curated, "in the
 * same style as `Design` and for the same reason: generated pages must not be allowed to
 * determine navigation order". Autogenerating it from the emitted directory would order
 * pages by filename, which is a fact about slugs rather than a decision about reading
 * order.
 *
 * Hand-curated does not have to mean written twice. Both `gen-reference.mjs` and
 * `astro.config.mjs` import this file: the generator buckets the description artifacts into
 * these pages, the config builds the sidebar from the same list. Editing the order here
 * moves the page and its navigation entry together, and a group that has navigation but no
 * page — or a page nothing links to — is not expressible.
 *
 * This module is deliberately data plus two pure functions, with no `node:` imports, so the
 * Astro config can import it in the browser-facing build without dragging filesystem code
 * along.
 */

/**
 * A generated page.
 *
 * @typedef {object} ReferencePage
 * @property {string} slug Last path segment of the route, and the emitted file's basename.
 * @property {string} label Sidebar label and page title.
 * @property {string} description Frontmatter description, shown in search results.
 */

/**
 * The CLI pages, in reading order.
 *
 * One page rather than one per command: `capsule` has 16 commands whose help is a sentence
 * each, and sixteen pages of one paragraph would put the whole surface behind sixteen
 * clicks. The command tree is small enough to read end to end.
 *
 * @type {ReferencePage[]}
 */
export const CLI_PAGES = [
    {
        slug: 'commands',
        label: 'Commands',
        description:
            'Every capsule command, argument, and option, generated from the committed command tree.',
    },
];

/**
 * A generated REST page: one endpoint family, with the path prefixes that belong to it.
 *
 * @typedef {ReferencePage & { pathPrefixes: string[] }} ApiGroup
 */

/**
 * The REST pages, in reading order — a client's order, not the document's: what version you
 * are talking to, what the server advertises, how to authenticate, then the data plane, then
 * the account surfaces.
 *
 * Grouped by hand because there is nothing to group by automatically. The Kynos document
 * carries no `tags` on any of its 59 operations, so an autogenerated section would be 59
 * pages ordered by filename — which `design/developer-docs.md` forbids in as many words,
 * and which would scatter the four `/v1/upload` operations of one protocol across the
 * alphabet.
 *
 * The names track the surface map in `design/api-surfaces.md`, so a reader who arrives from
 * a design document finds the page named after the surface they were reading about.
 *
 * @type {ApiGroup[]}
 */
export const API_GROUPS = [
    {
        slug: 'version',
        label: 'Version',
        description:
            'The protocol handshake every client performs before it does anything else.',
        pathPrefixes: ['/v1/version'],
    },
    {
        slug: 'well-known',
        label: 'Server discovery',
        description:
            'What a server publishes about itself: attestation keys, capabilities, deprecations, and revoked tokens.',
        pathPrefixes: ['/.well-known/capsule/'],
    },
    {
        slug: 'auth',
        label: 'Authentication and devices',
        description:
            'Registration, sign-in, the second factor, session and device management, and key escrow.',
        pathPrefixes: ['/v1/auth/'],
    },
    {
        slug: 'upload',
        label: 'Upload',
        description:
            'The resumable, encrypted upload protocol: open a session, drive it, and read its receipt.',
        pathPrefixes: ['/v1/upload'],
    },
    {
        slug: 'albums',
        label: 'Albums and lifecycle writes',
        description:
            'Album creation, the lifecycle write surface, and the membership upgrade handshake.',
        pathPrefixes: ['/v1/albums'],
    },
    {
        slug: 'sync',
        label: 'Sync and blob fetch',
        description:
            'The change feed a client drains after a cursor, and the range-capable blob endpoint it fetches from.',
        pathPrefixes: ['/v1/sync', '/v1/blob/'],
    },
    {
        slug: 'storage',
        label: 'Storage verification',
        description:
            'Proving the server still holds what it said it held, and the receipts that attest to it.',
        pathPrefixes: ['/v1/storage/', '/v1/assets/'],
    },
    {
        slug: 'shares',
        label: 'Share links',
        description:
            'Issuing and revoking a share link, and the unauthenticated surface that serves one.',
        pathPrefixes: ['/v1/shares', '/s/'],
    },
    {
        slug: 'drops',
        label: 'Guest drops',
        description:
            'Guest upload links, the unauthenticated drop surface, and the owner-side inbox and adoption.',
        pathPrefixes: ['/v1/drops', '/d/'],
    },
    {
        slug: 'quota',
        label: 'Quota',
        description: 'What the account has used, and what it is allowed.',
        pathPrefixes: ['/v1/quota'],
    },
    {
        slug: 'moderation',
        label: 'Moderation',
        description:
            "The account's own moderation record — every action taken against it, in order.",
        pathPrefixes: ['/v1/moderation/'],
    },
];

/**
 * The group a path belongs to, by longest matching prefix, or `null` when none matches.
 *
 * Longest-prefix rather than first-match so the table's *reading* order and its *matching*
 * order are independent. First-match would make adding a narrower group — `/v1/auth/totp/`
 * under `/v1/auth/` — silently depend on placing it above the broader one, which is a trap
 * a reader reordering the table for navigation reasons would spring without noticing.
 *
 * @param {string} path An OpenAPI path template, e.g. `/v1/albums/{album_id}/ops`.
 * @returns {ApiGroup | null}
 */
export function groupForPath(path) {
    let best = null;
    let bestLength = -1;
    for (const group of API_GROUPS) {
        for (const prefix of group.pathPrefixes) {
            if (path.startsWith(prefix) && prefix.length > bestLength) {
                best = group;
                bestLength = prefix.length;
            }
        }
    }
    return best;
}

/**
 * Sidebar items for the `Reference` group, in the order they are read.
 *
 * Returns Starlight sidebar entries: the section overview first, then one nested group per
 * surface whose own overview leads its generated pages.
 *
 * @returns {Array<{ slug: string } | { label: string, items: Array<{ slug: string }> }>}
 */
export function referenceSidebar() {
    return [
        { slug: 'reference' },
        {
            label: 'CLI',
            items: [
                { slug: 'reference/cli' },
                ...CLI_PAGES.map((page) => ({
                    slug: `reference/cli/${page.slug}`,
                })),
            ],
        },
        {
            label: 'REST API',
            items: [
                { slug: 'reference/api' },
                ...API_GROUPS.map((group) => ({
                    slug: `reference/api/${group.slug}`,
                })),
            ],
        },
    ];
}
