//! GENERATED by `cargo run -p xtask -- i18n` from `locales/`. Do not edit by hand.
//!
//! Run `just i18n` to regenerate after changing the catalogs.

/// The source (authoring) locale; the final fallback for every lookup.
pub(crate) const SOURCE_LOCALE: &str = "en";

/// Supported locales, in `locales/config.json` order.
pub(crate) const SUPPORTED_LOCALES: &[&str] = &["en"];

/// `(locale, json)` pairs. Each `json` is a flat `{ key: message }` object.
pub(crate) const BUNDLES: &[(&str, &str)] = &[("en", include_str!("bundles/en.json"))];

/// Stable error codes — the `error.*` namespace of the message catalog.
///
/// The server attaches one of these as `ApiError.code`; clients map it to a
/// localized high-level message. Generated from the source catalog.
pub mod error_codes {
    /// `error.auth.invalid_credentials`
    pub const AUTH_INVALID_CREDENTIALS: &str = "error.auth.invalid_credentials";

    /// `error.auth.rate_limited`
    pub const AUTH_RATE_LIMITED: &str = "error.auth.rate_limited";

    /// `error.auth.user_already_exists`
    pub const AUTH_USER_ALREADY_EXISTS: &str = "error.auth.user_already_exists";
}
