//! GENERATED by `cargo run -p xtask -- i18n` from `locales/`. Do not edit by hand.
//!
//! Run `mise run i18n` to regenerate after changing the catalogs.

/// The source (authoring) locale; the final fallback for every lookup.
pub(crate) const SOURCE_LOCALE: &str = "en";

/// Supported locales, in `locales/config.json` order.
pub(crate) const SUPPORTED_LOCALES: &[&str] = &[
    "en", "zh-Hans", "zh-Hant", "ja", "ko", "fr", "de", "es", "pt-BR", "it", "ru", "hi", "ar",
];

/// `(locale, json)` pairs. Each `json` is a flat `{ key: message }` object.
pub(crate) const BUNDLES: &[(&str, &str)] = &[
    ("en", include_str!("bundles/en.json")),
    ("zh-Hans", include_str!("bundles/zh-Hans.json")),
    ("zh-Hant", include_str!("bundles/zh-Hant.json")),
    ("ja", include_str!("bundles/ja.json")),
    ("ko", include_str!("bundles/ko.json")),
    ("fr", include_str!("bundles/fr.json")),
    ("de", include_str!("bundles/de.json")),
    ("es", include_str!("bundles/es.json")),
    ("pt-BR", include_str!("bundles/pt-BR.json")),
    ("it", include_str!("bundles/it.json")),
    ("ru", include_str!("bundles/ru.json")),
    ("hi", include_str!("bundles/hi.json")),
    ("ar", include_str!("bundles/ar.json")),
];

/// Stable error codes — the `error.*` namespace of the message catalog.
///
/// The server attaches one of these as `ApiError.code`; clients map it to a
/// localized high-level message. Generated from the source catalog.
pub mod error_codes {
    /// `error.auth.invalid_credentials`
    pub const AUTH_INVALID_CREDENTIALS: &str = "error.auth.invalid_credentials";

    /// `error.auth.rate_limited`
    pub const AUTH_RATE_LIMITED: &str = "error.auth.rate_limited";

    /// `error.auth.revoke_proof_invalid`
    pub const AUTH_REVOKE_PROOF_INVALID: &str = "error.auth.revoke_proof_invalid";

    /// `error.auth.revoke_proof_required`
    pub const AUTH_REVOKE_PROOF_REQUIRED: &str = "error.auth.revoke_proof_required";

    /// `error.auth.user_already_exists`
    pub const AUTH_USER_ALREADY_EXISTS: &str = "error.auth.user_already_exists";

    /// `error.blob.pending_upload`
    pub const BLOB_PENDING_UPLOAD: &str = "error.blob.pending_upload";

    /// `error.directory.malformed`
    pub const DIRECTORY_MALFORMED: &str = "error.directory.malformed";

    /// `error.directory.version_conflict`
    pub const DIRECTORY_VERSION_CONFLICT: &str = "error.directory.version_conflict";

    /// `error.drop.cap_exceeded`
    pub const DROP_CAP_EXCEEDED: &str = "error.drop.cap_exceeded";

    /// `error.drop.malformed_descriptor`
    pub const DROP_MALFORMED_DESCRIPTOR: &str = "error.drop.malformed_descriptor";

    /// `error.drop.not_in_inbox`
    pub const DROP_NOT_IN_INBOX: &str = "error.drop.not_in_inbox";

    /// `error.drop.passphrase_required`
    pub const DROP_PASSPHRASE_REQUIRED: &str = "error.drop.passphrase_required";

    /// `error.drop.rate_limited`
    pub const DROP_RATE_LIMITED: &str = "error.drop.rate_limited";

    /// `error.enrollment.channel_not_found`
    pub const ENROLLMENT_CHANNEL_NOT_FOUND: &str = "error.enrollment.channel_not_found";

    /// `error.enrollment.code_refused`
    pub const ENROLLMENT_CODE_REFUSED: &str = "error.enrollment.code_refused";

    /// `error.enrollment.local_auth_required`
    pub const ENROLLMENT_LOCAL_AUTH_REQUIRED: &str = "error.enrollment.local_auth_required";

    /// `error.enrollment.rate_limited`
    pub const ENROLLMENT_RATE_LIMITED: &str = "error.enrollment.rate_limited";

    /// `error.enrollment.relay_malformed`
    pub const ENROLLMENT_RELAY_MALFORMED: &str = "error.enrollment.relay_malformed";

    /// `error.escrow.malformed`
    pub const ESCROW_MALFORMED: &str = "error.escrow.malformed";

    /// `error.federation.audience_mismatch`
    pub const FEDERATION_AUDIENCE_MISMATCH: &str = "error.federation.audience_mismatch";

    /// `error.federation.capability_expired`
    pub const FEDERATION_CAPABILITY_EXPIRED: &str = "error.federation.capability_expired";

    /// `error.federation.capability_invalid`
    pub const FEDERATION_CAPABILITY_INVALID: &str = "error.federation.capability_invalid";

    /// `error.federation.capability_revoked`
    pub const FEDERATION_CAPABILITY_REVOKED: &str = "error.federation.capability_revoked";

    /// `error.federation.circuit_open`
    pub const FEDERATION_CIRCUIT_OPEN: &str = "error.federation.circuit_open";

    /// `error.federation.rate_budget_exceeded`
    pub const FEDERATION_RATE_BUDGET_EXCEEDED: &str = "error.federation.rate_budget_exceeded";

    /// `error.federation.scope_insufficient`
    pub const FEDERATION_SCOPE_INSUFFICIENT: &str = "error.federation.scope_insufficient";

    /// `error.moderation.account_suspended`
    pub const MODERATION_ACCOUNT_SUSPENDED: &str = "error.moderation.account_suspended";

    /// `error.moderation.report_rate_limited`
    pub const MODERATION_REPORT_RATE_LIMITED: &str = "error.moderation.report_rate_limited";

    /// `error.moderation.report_unsigned`
    pub const MODERATION_REPORT_UNSIGNED: &str = "error.moderation.report_unsigned";

    /// `error.moderation.server_blocked`
    pub const MODERATION_SERVER_BLOCKED: &str = "error.moderation.server_blocked";

    /// `error.protocol.version_unsupported`
    pub const PROTOCOL_VERSION_UNSUPPORTED: &str = "error.protocol.version_unsupported";

    /// `error.quota.exceeded`
    pub const QUOTA_EXCEEDED: &str = "error.quota.exceeded";

    /// `error.quota.grace_locked`
    pub const QUOTA_GRACE_LOCKED: &str = "error.quota.grace_locked";

    /// `error.quota.peer_budget_exceeded`
    pub const QUOTA_PEER_BUDGET_EXCEEDED: &str = "error.quota.peer_budget_exceeded";

    /// `error.share.rate_limited`
    pub const SHARE_RATE_LIMITED: &str = "error.share.rate_limited";

    /// `error.storage.deep_rate_limited`
    pub const STORAGE_DEEP_RATE_LIMITED: &str = "error.storage.deep_rate_limited";

    /// `error.storage.invalid_request`
    pub const STORAGE_INVALID_REQUEST: &str = "error.storage.invalid_request";

    /// `error.sync.cursor_invalid`
    pub const SYNC_CURSOR_INVALID: &str = "error.sync.cursor_invalid";

    /// `error.sync.unauthenticated`
    pub const SYNC_UNAUTHENTICATED: &str = "error.sync.unauthenticated";

    /// `error.upload.album_access_denied`
    pub const UPLOAD_ALBUM_ACCESS_DENIED: &str = "error.upload.album_access_denied";

    /// `error.upload.amk_regressed`
    pub const UPLOAD_AMK_REGRESSED: &str = "error.upload.amk_regressed";

    /// `error.upload.checksum_mismatch`
    pub const UPLOAD_CHECKSUM_MISMATCH: &str = "error.upload.checksum_mismatch";

    /// `error.upload.chunk_conflict`
    pub const UPLOAD_CHUNK_CONFLICT: &str = "error.upload.chunk_conflict";

    /// `error.upload.chunk_not_aligned`
    pub const UPLOAD_CHUNK_NOT_ALIGNED: &str = "error.upload.chunk_not_aligned";

    /// `error.upload.chunk_too_large`
    pub const UPLOAD_CHUNK_TOO_LARGE: &str = "error.upload.chunk_too_large";

    /// `error.upload.content_hash_mismatch`
    pub const UPLOAD_CONTENT_HASH_MISMATCH: &str = "error.upload.content_hash_mismatch";

    /// `error.upload.device_not_authorized`
    pub const UPLOAD_DEVICE_NOT_AUTHORIZED: &str = "error.upload.device_not_authorized";

    /// `error.upload.duplicate_blob`
    pub const UPLOAD_DUPLICATE_BLOB: &str = "error.upload.duplicate_blob";

    /// `error.upload.empty_chunk`
    pub const UPLOAD_EMPTY_CHUNK: &str = "error.upload.empty_chunk";

    /// `error.upload.envelope_mismatch`
    pub const UPLOAD_ENVELOPE_MISMATCH: &str = "error.upload.envelope_mismatch";

    /// `error.upload.envelope_rejected`
    pub const UPLOAD_ENVELOPE_REJECTED: &str = "error.upload.envelope_rejected";

    /// `error.upload.file_too_large`
    pub const UPLOAD_FILE_TOO_LARGE: &str = "error.upload.file_too_large";

    /// `error.upload.finalize_in_progress`
    pub const UPLOAD_FINALIZE_IN_PROGRESS: &str = "error.upload.finalize_in_progress";

    /// `error.upload.forbidden`
    pub const UPLOAD_FORBIDDEN: &str = "error.upload.forbidden";

    /// `error.upload.invalid_action`
    pub const UPLOAD_INVALID_ACTION: &str = "error.upload.invalid_action";

    /// `error.upload.invalid_hash`
    pub const UPLOAD_INVALID_HASH: &str = "error.upload.invalid_hash";

    /// `error.upload.invalid_size`
    pub const UPLOAD_INVALID_SIZE: &str = "error.upload.invalid_size";

    /// `error.upload.malformed_request`
    pub const UPLOAD_MALFORMED_REQUEST: &str = "error.upload.malformed_request";

    /// `error.upload.missing_checksum`
    pub const UPLOAD_MISSING_CHECKSUM: &str = "error.upload.missing_checksum";

    /// `error.upload.missing_offset`
    pub const UPLOAD_MISSING_OFFSET: &str = "error.upload.missing_offset";

    /// `error.upload.offset_mismatch`
    pub const UPLOAD_OFFSET_MISMATCH: &str = "error.upload.offset_mismatch";

    /// `error.upload.owner_not_permitted`
    pub const UPLOAD_OWNER_NOT_PERMITTED: &str = "error.upload.owner_not_permitted";

    /// `error.upload.receipt_not_available`
    pub const UPLOAD_RECEIPT_NOT_AVAILABLE: &str = "error.upload.receipt_not_available";

    /// `error.upload.session_not_active`
    pub const UPLOAD_SESSION_NOT_ACTIVE: &str = "error.upload.session_not_active";

    /// `error.upload.session_not_found`
    pub const UPLOAD_SESSION_NOT_FOUND: &str = "error.upload.session_not_found";

    /// `error.upload.size_exceeded`
    pub const UPLOAD_SIZE_EXCEEDED: &str = "error.upload.size_exceeded";

    /// `error.upload.stale_revival`
    pub const UPLOAD_STALE_REVIVAL: &str = "error.upload.stale_revival";

    /// `error.upload.storage_inconsistent`
    pub const UPLOAD_STORAGE_INCONSISTENT: &str = "error.upload.storage_inconsistent";

    /// `error.upload.timestamp_out_of_range`
    pub const UPLOAD_TIMESTAMP_OUT_OF_RANGE: &str = "error.upload.timestamp_out_of_range";

    /// `error.upload.unknown_crypto_suite`
    pub const UPLOAD_UNKNOWN_CRYPTO_SUITE: &str = "error.upload.unknown_crypto_suite";

    /// `error.upload.unsupported_content_type`
    pub const UPLOAD_UNSUPPORTED_CONTENT_TYPE: &str = "error.upload.unsupported_content_type";

    /// `error.upload.unsupported_media_type`
    pub const UPLOAD_UNSUPPORTED_MEDIA_TYPE: &str = "error.upload.unsupported_media_type";
}
